nvme/023: use consistent coding style
Signed-off-by: Chaitanya Kulkarni <chaitanya.kulkarni@wdc.com>

diff --git a/tests/nvme/023 b/tests/nvme/023
--- a/tests/nvme/023
+++ b/tests/nvme/023
@@ -41,11 +41,11 @@ test() {
 	cat "/sys/block/${nvmedev}n1/uuid"
 	cat "/sys/block/${nvmedev}n1/wwid"
 
-	nvme smart-log "/dev/${nvmedev}" -n 1 > /dev/null 2>&1
+	if ! nvme smart-log "/dev/${nvmedev}" -n 1 >> "$FULL" 2>&1; then
+		echo "ERROR: smart-log bdev-ns failed"
+	fi
 
-	rc=$?
-
-	nvme disconnect -n "${subsys_name}"
+	nvme disconnect -n "${subsys_name}" >> "$FULL" 2>&1
 
 	_remove_nvmet_subsystem_from_port "${port}" "${subsys_name}"
 	_remove_nvmet_subsystem "${subsys_name}"
@@ -58,9 +58,5 @@ test() {
 	modprobe -r nvme-loop
 	modprobe -r nvmet
 
-	if [ $rc -ne 0 ]; then
-		echo "Test Failed"
-	else
-		echo "Test complete"
-	fi
+	echo "Test complete"
 }
