nvme/028: use consistent coding style
Signed-off-by: Chaitanya Kulkarni <chaitanya.kulkarni@wdc.com>

diff --git a/tests/nvme/028 b/tests/nvme/028
--- a/tests/nvme/028
+++ b/tests/nvme/028
@@ -38,11 +38,10 @@ test() {
 	cat "/sys/block/${nvmedev}n1/uuid"
 	cat "/sys/block/${nvmedev}n1/wwid"
 
-	nvme list-subsys | grep -q loop
-
-	rc=$?
-
-	nvme disconnect -n "${subsys_name}"
+	if ! nvme list-subsys 2>> "$FULL" | grep -q loop; then
+		echo "ERROR: list-subsys"
+	fi
+	nvme disconnect -n "${subsys_name}" >> "$FULL" 2>&1
 
 	_remove_nvmet_subsystem_from_port "${port}" "${subsys_name}"
 	_remove_nvmet_subsystem "${subsys_name}"
@@ -53,9 +52,5 @@ test() {
 	modprobe -r nvme-loop
 	modprobe -r nvmet
 
-	if [ $rc -ne 0 ]; then
-		echo "Test Failed"
-	else
-		echo "Test complete"
-	fi
+	echo "Test complete"
 }
