nvme: Add passthru error logging tests to nvme/039
Tests the ability to enable and disable error logging for passthru admin
commands issued to the controller and passthru IO commands issued to a
namespace.

These tests will only be run on kernels that export the
passthru_err_log_enabled attribute.

Signed-off-by: Alan Adamson <alan.adamson@oracle.com>
Reviewed-by: Chaitanya Kulkarni <kch@nvidia.com>
Signed-off-by: Shin'ichiro Kawasaki <shinichiro.kawasaki@wdc.com>

diff --git a/tests/nvme/039 b/tests/nvme/039
--- a/tests/nvme/039
+++ b/tests/nvme/039
@@ -130,6 +130,29 @@ inject_invalid_admin_cmd()
 	fi
 }
 
+inject_invalid_io_cmd_passthru()
+{
+	local ns
+
+	ns=$(echo "$1" |  cut -d "n" -f3)
+
+	# Inject a 'Invalid Command Opcode' (0x1) on a read (0x02)
+	_nvme_enable_err_inject "$ns_dev" 0 100 1 0x1 1
+
+	nvme io-passthru /dev/"$1" --opcode=0x02 --namespace-id="$ns" \
+		--data-len=512 --read --cdw10=0 --cdw11=0 --cdw12="$2" 2> /dev/null 1>&2
+
+	_nvme_disable_err_inject "$1"
+	if ${nvme_verbose_errors}; then
+		last_dmesg 2 | grep "Invalid Command Opcode (" | \
+		    sed 's/nvme.*://g'
+	else
+		last_dmesg 2 | grep "Cmd(0x2" | sed 's/I\/O Cmd/Read/g' | \
+		    sed 's/I\/O Error/Invalid Command Opcode/g' | \
+		    sed 's/nvme.*://g'
+	fi
+}
+
 test_device() {
 	echo "Running ${TEST_NAME}"
 
@@ -155,6 +178,26 @@ test_device() {
 	inject_invalid_status_on_read "${ns_dev}"
 	inject_write_fault_on_write "${ns_dev}"
 
+	if [ -e "$TEST_DEV_SYSFS/passthru_err_log_enabled" ]; then
+		_nvme_passthru_logging_setup "${ns_dev}" "${ctrl_dev}"
+
+		# Test Pass Thru Admin Logging
+		_nvme_disable_passthru_admin_error_logging "${ctrl_dev}"
+		inject_invalid_admin_cmd "${ctrl_dev}"
+		_nvme_enable_passthru_admin_error_logging "${ctrl_dev}"
+		inject_access_denied_on_identify "${ctrl_dev}"
+
+		# Test Pass Thru IO Logging
+		_nvme_disable_passthru_io_error_logging "${ns_dev}" "${ctrl_dev}"
+		inject_invalid_io_cmd_passthru "${ns_dev}" 0
+		_nvme_enable_passthru_io_error_logging "${ns_dev}" "${ctrl_dev}"
+		inject_invalid_io_cmd_passthru "${ns_dev}" 1
+
+		_nvme_passthru_logging_cleanup "${ns_dev}" "${ctrl_dev}"
+	else
+		echo " Identify(0x6), Access Denied (sct 0x2 / sc 0x86) DNR cdw10=0x1 cdw11=0x0 cdw12=0x0 cdw13=0x0 cdw14=0x0 cdw15=0x0"
+		echo " Read(0x2), Invalid Command Opcode (sct 0x0 / sc 0x1) DNR cdw10=0x0 cdw11=0x0 cdw12=0x1 cdw13=0x0 cdw14=0x0 cdw15=0x0"
+	fi
 	_nvme_err_inject_cleanup "${ns_dev}" "${ctrl_dev}"
 
 	echo "Test complete"
