block/008: Better fix for osandov/blktests#28
I'm constantly hitting this problem:

	block/008 => sdb (do IO while hotplugging CPUs)              [failed]
	    runtime    ...  258.910s
	    --- tests/block/008.out     2018-12-06 07:52:28.971820224 +0500
	    +++ /root/blktests/results/sdb/block/008.out.bad    2018-12-09 19:25:08.973348308 +0500
	    @@ -1,2 +1,4 @@
	     Running block/008
	    +clock setaffinity failed: Invalid argument
	    +_fio_perf: too many terse lines
	     Test complete

It seems that 0.2 second sleep is not enough because my system is too slow.

Instead of adding more sleep, this patch implements proper (I hope so)
logic that waits until fio opens the test device.

Signed-off-by: Ivan Mironov <mironov.ivan@gmail.com>

diff --git a/tests/block/008 b/tests/block/008
--- a/tests/block/008
+++ b/tests/block/008
@@ -41,6 +41,13 @@ test_device() {
 		fi
 	done
 
+	# Ensure that fio has started doing actual IO.
+	while kill -0 $! 2> /dev/null; do
+		_is_fio_running "$TEST_DEV" && break
+		sleep .2
+	done
+	kill -0 $! 2> /dev/null || echo "failure: fio terminated unexpectedly"
+
 	# while job is running, hotplug CPUs
 	while sleep .2; kill -0 $! 2> /dev/null; do
 		if (( offlining && ${#offline_cpus[@]} == max_offline )); then
