block/032: make error messages clearer if mkfs or mount fails
If block/032 fails at mkfs we want to know why, so propagate
error messages. While at it, enhance the test to also propagate
the error return from mount and remove the odd sleep for a udevadm
settle as that's the only thing I can think of we need to wait for
here.

Signed-off-by: Luis Chamberlain <mcgrof@kernel.org>
[Shin'ichiro: enriched _xfs_mkfs_and_mount failure handling]
Signed-off-by: Shin'ichiro Kawasaki <shinichiro.kawasaki@wdc.com>

diff --git a/tests/block/032 b/tests/block/032
--- a/tests/block/032
+++ b/tests/block/032
@@ -20,15 +20,22 @@ requires() {
 test() {
 	echo "Running ${TEST_NAME}"
 
+	local ret
+
 	if ! _init_scsi_debug dev_size_mb=300; then
 		return 1
 	fi
 
 	mkdir -p "${TMPDIR}/mnt"
-	_xfs_mkfs_and_mount "/dev/${SCSI_DEBUG_DEVICES[0]}" "${TMPDIR}/mnt" > /dev/null 2>&1
+	if ! _xfs_mkfs_and_mount "/dev/${SCSI_DEBUG_DEVICES[0]}" "${TMPDIR}/mnt" >> "$FULL"; then
+		ret=$?
+		echo "_xfs_mkfs_and_mount failed"
+		_exit_scsi_debug
+		return $ret
+	fi
 	echo 1 > "/sys/block/${SCSI_DEBUG_DEVICES[0]}/device/delete"
-	sleep 2
-	umount "${TMPDIR}/mnt"
+	udevadm settle
+	umount "${TMPDIR}/mnt" || return $?
 
 	_exit_scsi_debug
 
